# Generated by Django 5.1.3 on 2024-11-16 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("postgres_db_django_app", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="publication",
            name="data",
            field=models.JSONField(null=True),
        ),
    ]
