# Generated by Django 5.1.3 on 2024-11-16 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("postgres_db_django_app", "0004_crop_metricscategory_orderedranking_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="crop",
            name="emission_data",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="crop",
            name="emissions",
            field=models.FloatField(blank=True, null=True),
        ),
    ]
