# Generated by Django 5.1.3 on 2024-11-16 23:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("postgres_db_django_app", "0005_crop_emission_data_crop_emissions"),
    ]

    operations = [
        migrations.AlterField(
            model_name="crop",
            name="name",
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
