# Generated by Django 5.1.3 on 2024-11-17 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("postgres_db_django_app", "0006_alter_crop_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="crop",
            name="mentioned_in_world_bank",
            field=models.BooleanField(default=False),
        ),
    ]
