# Generated by Django 5.1.3 on 2024-11-17 00:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("postgres_db_django_app", "0007_crop_mentioned_in_world_bank"),
    ]

    operations = [
        migrations.AddField(
            model_name="metric",
            name="crop",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="metrics",
                to="postgres_db_django_app.crop",
            ),
        ),
    ]
