# Generated by Django 5.1.3 on 2024-11-17 01:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "postgres_db_django_app",
            "0010_metric_notes_metric_publication_metric_units_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="searchterm",
            name="metrics_category",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="search_terms",
                to="postgres_db_django_app.metricscategory",
            ),
        ),
    ]
