# Generated by Django 5.1.3 on 2024-11-17 02:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("postgres_db_django_app", "0012_searchterm_metrics_subcategory"),
    ]

    operations = [
        migrations.CreateModel(
            name="SearchResults",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "crop",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="search_results",
                        to="postgres_db_django_app.crop",
                    ),
                ),
                (
                    "journal",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="search_results",
                        to="postgres_db_django_app.publicationjournal",
                    ),
                ),
                (
                    "publications",
                    models.ManyToManyField(
                        related_name="search_results",
                        to="postgres_db_django_app.publication",
                    ),
                ),
                (
                    "search_term",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="search_results",
                        to="postgres_db_django_app.searchterm",
                    ),
                ),
            ],
            options={
                "unique_together": {("search_term", "crop", "journal")},
            },
        ),
    ]
