# Generated by Django 5.1.3 on 2024-11-17 02:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("postgres_db_django_app", "0013_searchresults"),
    ]

    operations = [
        migrations.AddField(
            model_name="publication",
            name="journal",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="publications",
                to="postgres_db_django_app.publicationjournal",
            ),
        ),
    ]
